name : github-actions-demo
on: [push]
jobs:
   build:
    runs-on: ubuntu-latest
    steps:

   - run: python --version
   - uses: actions/checkout@v3

   - name: extensions instalation
     run: |
       python -m pip install --upgrade pip
       pip install pylint
       pip install flask
       pip install -r requirements.txt
  - name:
       pylint app.py
